# Generated by Django 5.2.6 on 2025-10-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_terms_accepted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="whatsapp",
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
