# Generated by Django 5.2.6 on 2025-12-14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_shortlink_alter_userprofile_whatsapp"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_completed_slide_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_interaction_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="progress_mode",
            field=models.CharField(
                choices=[("FREE", "Avanco livre"), ("MONITORED", "Avanco monitorado")],
                default="FREE",
                help_text="Define se o aluno avanca livremente ou precisa cumprir tempo/interacoes.",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="progress_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slide_id", models.IntegerField(db_index=True)),
                ("elements", models.JSONField(blank=True, default=dict)),
                ("time_met", models.BooleanField(default=False)),
                ("required_seconds", models.IntegerField(default=0)),
                ("completed", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="progress_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["slide_id"],
                "unique_together": {("user", "slide_id")},
            },
        ),
    ]
