# Generated by Django 5.2.6 on 2025-12-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_progress_controls"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_viewed_slide_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
