# Generated by Codex on 2026-01-16

import json
from pathlib import Path

from django.conf import settings
from django.db import migrations


def _get_default_product_id():
    data_path = Path(settings.BASE_DIR) / "protected" / "data.json"
    try:
        with data_path.open(encoding="utf-8") as handle:
            payload = json.load(handle)
        product_id = payload.get("productId")
        if product_id:
            return str(product_id)
    except Exception:
        pass
    return "000001"


def seed_default_course(apps, schema_editor):
    Course = apps.get_model("accounts", "Course")
    Enrollment = apps.get_model("accounts", "Enrollment")
    CustomUser = apps.get_model("accounts", "CustomUser")
    UserProfile = apps.get_model("accounts", "UserProfile")
    UserProgress = apps.get_model("accounts", "UserProgress")

    product_id = _get_default_product_id()
    course, _ = Course.objects.get_or_create(
        product_id=product_id,
        defaults={"is_default": True, "is_active": True},
    )
    if not course.is_default:
        course.is_default = True
        course.save(update_fields=["is_default"])

    profiles_by_user = {profile.user_id: profile for profile in UserProfile.objects.all()}

    for user in CustomUser.objects.all():
        if Enrollment.objects.filter(user_id=user.id, course_id=course.id).exists():
            continue
        profile = profiles_by_user.get(user.id)
        Enrollment.objects.create(
            user_id=user.id,
            course_id=course.id,
            progress_mode=getattr(profile, "progress_mode", "FREE"),
            last_viewed_slide_id=getattr(profile, "last_viewed_slide_id", None),
            last_completed_slide_id=getattr(profile, "last_completed_slide_id", None),
            last_interaction_at=getattr(profile, "last_interaction_at", None),
        )

    UserProgress.objects.filter(course__isnull=True).update(course_id=course.id)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_course_alter_userprogress_unique_together_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_default_course, migrations.RunPython.noop),
    ]
