# Generated by Codex on 2026-01-16

from django.db import migrations, models
import django.db.models.deletion


def set_course_for_progress(apps, schema_editor):
    Course = apps.get_model("accounts", "Course")
    UserProgress = apps.get_model("accounts", "UserProgress")

    course = Course.objects.filter(is_default=True, is_active=True).first()
    if not course:
        course = Course.objects.filter(is_active=True).first()
    if not course:
        course = Course.objects.create(product_id="000001", is_default=True, is_active=True)

    UserProgress.objects.filter(course__isnull=True).update(course_id=course.id)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_seed_default_course_and_enrollments"),
    ]

    operations = [
        migrations.RunPython(set_course_for_progress, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="userprogress",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress_entries",
                to="accounts.course",
            ),
        ),
    ]
